### ISSUE TITLE
Please add Auth0-Lock

### ISSUE THREAD

**Issue by virtualirfan** [DefinitelyScala/scala-js-template#2]
Request to please add [Auth0-Lock](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/auth0-lock) to the list of generated Scala-js facades.

Thanks,

**Comment by KyleU** [comment]
Added: https://github.com/DefinitelyScala/scala-js-auth0lock

It's busted right now, but I'll work to fix it.

**Comment by virtualirfan** [comment]
OK, thanks. If you document what's broken, might be able to offer help.

**Comment by KyleU** [comment]
The immediate problem is that `auth0` isn't published for 2.12, I'm fixing that tonight. After that, there's a few import errors. I usually have to hand-tune projects before they're published.
