### ISSUE TITLE
Replace @js.native with @ScalaJSDefined?

### ISSUE THREAD

**Issue by virtualirfan** [DefinitelyScala/scala-js-template#3]
As an example, the generated Scala.js facades for Auth0.js have this [trait](https://github.com/DefinitelyScala/scala-js-auth0js/blob/master/src/main/scala/com/definitelyscala/auth0js/auth0/AuthOptions.scala):
```Scala
@js.native
trait AuthOptions extends js.Object {
  var domain: String = js.native
…
}
```
The fact that the trait is marked @js.native makes it hard (impossible?) to subclass with with a ```class``` and then instantiate it.

I tried this:
```Scala
@js.native
@JSGlobal
class Opts2 extends auth0.AuthOptions {
  domain = "<elided>"
}
```
and instantiated like this:
```Scala
     val oo = new Opts2
```
But I get this runtime error
```
Uncaught TypeError: $g.Opts2 is not a constructor
```
from here in the corresponding generated javascript file:
```Javascript
  new $g.Opts2()
```
As per [Export Scala.js APIs to JavaScript](http://www.scala-js.org/doc/interoperability/export-to-javascript.html) in the "Exporting classes" section, if I try to change the definition of class Opts2 to include a @JSExportTopLevel, I get the following error:
```
You may not export a native JS class or object
[error] @JSExportTopLevel("Opts2")
```
I posted this issue to the scala-js gitter channel and @sjrd said this:

> Yeah the facade should not be ```@js.native```. It should be ```@ScalaJSDefined.```

> Workaround: ```js.Dynamic.literal(domain = "foobar").asInstanceOf[AuthOptions]```

I'm using the workaround right now but ideally we fix it in the library for all users.

I'm also not sure why others aren't complaining about this … I tripped on this right away.

**Comment by sjrd** [comment]
In general, all JS *traits* should be `@ScalaJSDefined` by default. There are few good reasons to have an `@js.native trait`.

**Comment by KyleU** [comment]
Thanks for creating this issue. I've been using that workaround like a chump for months, I never knew there was a better way.

I've got it fixed so it applies @ScalaJSDefined to any traits. I'm declaring methods as abstract, which works well. However, I get warnings about the trait's `val`s and `var`s if I leave them abstract. Should I ignore the warnings, or change every var/val of type `T` to `UndefOr[T] = js.undefined`?

**Comment by sjrd** [comment]
What kind of warnings? There shouldn't be any warnings for that.

Actually a val/var with a `?` in TypeScript should be a `js.UndefOr[A]` with `= js.undefined`. And other val/vars should be abstract.

**Comment by KyleU** [comment]
I use some pretty pedantic code tools - It shows in scapegoat and in IntelliJ. Easy enough, I'll just leave them abstract, thanks for the quick response.

**Comment by KyleU** [comment]
How should I handle these JS features in a ScalaJSDefined trait?

 - `@JSBracketAccess is not allowed in Scala.js-defined JS classes`

 - `A Scala.js-defined JavaScript class cannot declare a method named "apply" without "@JSName"`

**Comment by sjrd** [comment]
If a trait has a bracket-access and/or an `apply` method, that's one of the rare good reasons to make it `@js.native` ;)

**Comment by KyleU** [comment]
Well, crap. Ok, I guess I can detect if it has an exotic method, and emit `js.native` for only those traits. Same issue with default arguments as well (foo: Int = js.native), I think.

**Comment by KyleU** [comment]
Most of the Scala.js traits I'm generating include default arguments, BracketAccess or an apply method. So I have to keep those using the old method (`@js.native`) for those. But since there's no easy way to extend a `@js.native` trait, I'm at an impasse. Closing this issue until a better solution comes along.
